### ISSUE TITLE
Metapath

### ISSUE THREAD

**Issue by DuanhaoranCC** [JHL-HUST/LMSPS#2]
Hello, I read your paper and have the following confusion:
1. https://github.com/JHL-HUST/LMSPS/blob/main/hgb/arch.py
Is the metapath arbitrarily defined or is there semantics in it?
2. in the model time computation part, is preprocessing, i.e. feature propagation, accounted for? The model has more preprocessing compared to HGT, HGB, etc.

Thank.

**Comment by lichaoaaron** [comment]
Thanks for your question.

Answer 1: 
The meta-path search space (candidate meta-paths) contains all target-node-related meta-paths without any prior. The file arch.py shows the meta-paths searched by our algorithm for each dataset. Each of them contains semantic information. The interpretability of these meta-paths can be found in the Appendix of our paper.

Answer 2: 
Following convention (Simple-HGN, SeHGNN),  we compare the training efficiency and we measure the time consumption of one epoch for each model. The main reason for this setting is the needed number of epochs until convergence could be various and hard to define exactly for various models. The total training time is positively related to epochs, so the total training time is hard to reflect the efficiency of a model. The preprocessing step doesn't contain weight training and can't be included in the one-epoch consumption version, so the preprocessing step is not included as in Simple-HGN and SeHGNN.
